apiVersion: batch/v1
kind: Job
metadata:
  name: api-tests
  namespace: updateandrollback
spec:
  template:
    metadata:
      name: api-tests
    spec:
      containers:
      - name: api-tests
        image: postman/newman:alpine
        command: ["/bin/sh"]
        args: ["-c", "newman run https://www.getpostman.com/collections/a861781dc9b36edf6715 --bail --reporters cli --reporter-cli-no-failures; test_status=$?; if [ $test_status != 0 ]; then exit 1; else echo \"TC Pass\"; fi;"]
      restartPolicy: Never
