apiVersion: batch/v1
kind: Job
metadata:
  name: api-tests
  namespace: updateandrollback
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 1
  template:
    metadata:
      name: api-tests
    spec:
      containers:
      - name: api-tests
        image: postman/newman:alpine
        command:
        - /bin/sh
        - -c
        - |
           newman run https://www.getpostman.com/collections/a861781dc9b36edf6715 | grep "AssertionError"  
          status=$?
          if [ $status -eq 0 ]; then exit 1; fi         
    restartPolicy: Never
