apiVersion: batch/v1
kind: Job
metadata:
  name: api-tests
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: api-tests
    spec:
      containers:
      - name: api-tests
        image: postman/newman:alpine
        command:
        - /bin/sh
        - -c
        - |
          newman run https://raw.githubusercontent.com/prabhat2410/Orion/master/Postman/CSP_Collection.postman_collection.json; status=$?; if [ $status -ne 0 ]; then exit 1; fi         
      restartPolicy: Never
