stages:
- name: Build and Publish
  steps:
  - publishImageConfig:
      dockerfilePath: docker/Dockerfile
      buildContext: .
      tag: orion-devops-image
      pushRemote: true
      registry: 192.168.100.176:5000
timeout: 60
notification: {}
