stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: docker/Dockerfile
      buildContext: .
      tag: fiware-orion
      pushRemote: true
      registry: 10.0.8.61:31484
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
- name: Postman test
  steps:
  - applyYamlConfig:
      path: Postman/Postman.yaml
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
- name: test_demo
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |
        echo "Hello world !!"
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
- name: jmeter test
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |
        apt-get update
        apt-get install sshpass
        sshpass -p mehant ssh -tt -o StrictHostKeyChecking=no mehant@192.168.100.178
        ping www.google.com
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
timeout: 60
notification: {}
