stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: docker/Dockerfile
      buildContext: .
      tag: fiware-orion-devops-image
      pushRemote: true
      registry: 192.168.100.176:5000
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
- name: Postman test
  steps:
  - applyYamlConfig:
      path: Postman/postman_test.yaml
    when:
      branch: {}
      event: {}
- name: test_demo
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: echo "Hello world !!"
    when:
      branch: {}
      event: {}
- name: jmeter test
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |-
        sh-keygen
        ssh-copy-id -i ~/.ssh/id_rsa.pub mehant@192.168.100.178
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
timeout: 60
notification: {}
