stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: docker/Dockerfile
      buildContext: .
      tag: fiware-orion:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 10.0.8.61:31484
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
- name: Test_postman
  steps:
  - applyYamlConfig:
      path: Postman/Postman.yaml
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
  - runScriptConfig:
      image: python:latest
      shellScript: "apt-get update\napt-get install sshpass \n\n\n\n\n\n\n\n\n\nsshpass
        -p mehant ssh -tt -o StrictHostKeyChecking=no mehant@192.168.100.178 << EOF\n\nkubectl
        --kubeconfig=config-176 get pods -n updateandrollback | grep \"api-test\"
        | cut -d \" \" -f1 |head -1\n\nkubectl --kubeconfig=config-176 logs $api_test_pod
        -n updateandrollback > /home/mehant/Test_Reports/postman_report__$(date \"+%Y.%m.%d-%H.%M.%S\")\n\nEOF\n\n\n"
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
- name: demo_test
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: echo "hello world"
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
- name: jmeter
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: "apt-get update\napt-get install sshpass\n\n#!/bin/bash\n#Script
        created to launch Jmeter tests directly from the current terminal without
        accessing the jmeter master pod.\n#It requires that you supply the path to
        the jmx file\n#After execution, test script jmx file may be deleted from the
        pod itself but not locally.\n\n\nsshpass -p mehant ssh -tt -o StrictHostKeyChecking=no
        mehant@192.168.100.178 << EOF\n\n\n\nsleep 30\n\necho \"aa\" >> file1\necho
        \"bb\" >> file2\necho \"cc\" >> file3\n\nworking_dir=\"`pwd`\"\n\n#Get namesapce
        variable\n#tenant=`awk '{print $NF}' \"$working_dir/tenant_export\"`\ntenent=\"jmeter\"\n#echo
        \"*** PWD ***\"\n#echo \"`pwd`\"\n\n#jmx=\"/home/mehant/Orion-new.jmx\"\n#if
        [ -n \"$jmx\" ] \n#             read -p 'Enter path to the jmx file ' \n#fi\n\n#if
        [ ! -f \"/home/mehant/Orion-new.jmx\" ];\n#then\n#    echo \"Test script file
        was not found in PATH\"\n#    echo \"Kindly check and input the correct file
        path\"\n#   exit\n#fi\n\n#test_name=\"$(basename \"$jmx\")\"\n\n#Get Master
        pod details\n\n\nmaster_pod=\"$(kubectl --kubeconfig=config-176 get po -n
        jmeter | grep jmeter-master | awk '{print $1}')\"\n\nkubectl --kubeconfig=config-176
        exec -ti -n jmeter $master_pod -- /bin/bash  /jmeter/apache-jmeter-5.0/bin/jmeter
        -n -t /jmeter/apache-jmeter-5.0/bin/Orion-new_test.jmx\n \nEOF\n"
    when:
      branch: {}
      event: {}
timeout: 60
notification: {}
