stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: docker/Dockerfile
      buildContext: .
      tag: fiware-orion:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 192.168.100.176
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: orion-devoperation
      registry: 127.0.0.1:34685
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
  when:
    event: {}
- name: UT
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |+
        apt-get update
        echo Y | apt-get install npm
        npm -v
        npm install -g newman
        newman run http://192.168.100.178/csp_containerizationandautomation/orion/raw/master/Context_State_in_Orion.postman_collection.json









    when:
      branch: {}
      event: {}
  when:
    event: {}
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    when:
      branch: {}
      event: {}
  - applyYamlConfig:
      path: service.yaml
    when:
      branch: {}
      event: {}
- name: Test
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |-
        apt-get update
        echo Y | apt-get install npm
        npm -v
        npm install -g newman
        newman run http://192.168.100.178/csp_containerizationandautomation/orion/raw/master/Context_State_in_Orion.postman_collection.json
timeout: 60
notification: {}
