stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: docker/Dockerfile
      buildContext: .
      tag: fiware-orion
      pushRemote: true
      registry: 127.0.0.1:34318
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      branch: {}
      event: {}
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
- name: Test
  steps:
  - applyYamlConfig:
      path: ./Postman.yaml
timeout: 60
notification: {}
