stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: docker/Dockerfile
      buildContext: .
      tag: fiware-orion:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 192.168.100.176
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: orion-devoperation
      registry: 127.0.0.1:34685
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
  - runScriptConfig:
      image: python:latest
      shellScript: |-
        #!/bin/bash

        echo "hello world richa" | awk '{print $3}'
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
  when:
    event: {}
- name: Test_postman
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: "# Stop on first error\n#set -e;\napt-get update\n\n#apt-get install
        curl\n#curl -sL https://deb.nodesource.com/setup_13.x \necho Y | apt-get install
        npm\n\nnpm -v\n\nnpm install -g newman\n\nnewman run https://www.getpostman.com/collections/a861781dc9b36edf6715\n#newman
        run https://raw.githubusercontent.com/prabhat2410/Orion/master/Postman/CSP_Collection.postman_collection.json\n\n\n\n\n\n\n\n\n\n"
    when:
      branch: {}
      event: {}
  when:
    event: {}
- name: demo_test
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: "#!/bin/bash\n\necho \"hello world richa\" "
    when:
      branch: {}
      event: {}
  when:
    event: {}
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
  - applyYamlConfig:
      path: service.yaml
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
timeout: 60
notification: {}
