stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: docker/Dockerfile
      buildContext: .
      tag: fiware-orion:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 10.0.8.61:31484
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
- name: Test_postman
  steps:
  - applyYamlConfig:
      path: Postman/Postman.yaml
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
- name: demo_test
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: echo "hello world"
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
- name: jmeter
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |-
        apt-get update
        apt-get install sshpass

        #!/usr/bin/env bash
        # Script created to launch Jmeter tests with csv data files directly from the current terminal without accessing the jmeter master pod.
        # It requires that you supply the path to the directory with jmx file and csv files
        # Directory structure of jmx with csv supposed to be:
        # _test_name_/
        # _test_name_/_test_name_.jmx
        # _test_name_/test_data1.csv
        # _test_name_/test_data2.csv
        # i.e. jmx file name have to be the same as directory name.
        # After execution, test script jmx file may be deleted from the pod itself but not locally.

        sshpass -p mehant ssh -tt -o StrictHostKeyChecking=no mehant@192.168.100.178 <<EOF

        ls;

        working_dir=$(pwd)

        # Get namesapce variable
        tenent="jmeter"
        tenant=$(awk '{print $NF}' "$working_dir"/tenant_export)
        jmx="/jmeter/apache-jmeter-5.0/bin/Orion-new.jmx"
        jmx_dir="/home/mehant/Orion-new.jmx"

        #if [ ! -f "/home/mehant/Orion-new.jmx" ];
        #then
        #    echo "Test script dir was not found"
        #    echo "Kindly check and input the correct file path"
        #    exit
        #fi

        # Get Master pod details

        printf "Copy %s to master\n" "${jmx_dir}.jmx"

        master_pod=`kubectl --kubeconfig=config-176 get po -n jmeter | grep jmeter-master | awk '{print \$1}'`

        kubectl --kubeconfig=config-176 exec -ti -n jmeter jmeter-master-7774f59cb4-9xqfk -- /bin/bash  /jmeter/apache-jmeter-5.0/bin/jmeter -n -t /jmeter/apache-jmeter-5.0/bin/Orion-new_test.jmx
    when:
      branch: {}
      event: {}
timeout: 60
notification: {}
