stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: docker/Dockerfile
      buildContext: .
      tag: fiware-orion:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 192.168.100.176
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: orion-devoperation
      registry: 127.0.0.1:34685
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
    when:
      branch:
        include:
        - master
      event:
        include:
        - pull_request
        - push
  - runScriptConfig:
      image: python:latest
      shellScript: |+
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        apt-get update
        apt-cache policy docker-ce
        apt-get install -y docker-ce
        systemctl status docker

        docker pull ansi/mosquitto
        docker pull mongo
        docker pull rabbitmq

        docker run -d -p 1883:1883   -l mosquitto ansi/mosquitto
        docker run -d -p 27017:27017 -l mongodb mongo
        docker run -d -p 5672:5672   -l rabbitmq rabbitmq

        apt-get update
        echo Y | apt-get install npm
        npm -v
        npm insatll -g
        npm install nock
        npm install should
        npm install mocha chai --save-dev
        npm test




  when:
    event: {}
- name: test
  steps:
  - runScriptConfig:
      image: python:latest
      shellScript: |+
        apt-get update
        echo Y | apt-get install npm
        npm -v
        npm install -g newman
        newman run http://192.168.100.178/csp_containerizationandautomation/orion/raw/master/Context_State_in_Orion.postman_collection.json









    when:
      branch: {}
      event: {}
  when:
    event: {}
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    when:
      branch: {}
      event: {}
  - applyYamlConfig:
      path: service.yaml
    when:
      branch: {}
      event: {}
timeout: 60
notification: {}
