apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: broker
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: broker
    spec:
      containers:
      
      - name: orion
        image: 192.168.100.176:5000/orion-devoperation
        resources:
         limits:
          memory: "500Mi"
          cpu: "500m"
         requests:
          memory: "250Mi"
          cpu: "250m"
        ports:
        - containerPort: 1026
        args: ["-dbhost", "mongo-0.mongo.ceph.svc.cluster.local:27017,mongo-1.mongo.ceph.svc.cluster.local:27017,mongo-2.mongo.ceph.svc.cluster.local:27017", "-rplSet" ,"rs0", "-logLevel", "DEBUG"]
