apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: broker
  namespace: ceph
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: broker
    spec:
      containers:
      
      - name: orion
        image: 10.0.8.61:31484/fiware-orion
        resources:
         limits:
          memory: "500Mi"
          cpu: "500m"
         requests:
          memory: "250Mi"
          cpu: "250m"
        ports:
        - containerPort: 1026
        args: ["-dbhost", "mongo-1.mongo,mongo-0.mongo,mongo-2.mongo", "-rplSet" ,"rs0", "-logLevel", "DEBUG"]
---

apiVersion: v1
kind: Service
metadata:
  name: orion-service
  namespace: ceph
  labels:
    name: orionservice-nodeport-svc
spec:
  type: NodePort
  ports:
    - port: 1026
      nodePort: 31444
      name: http
  selector:
    name: broker
