apiVersion: v1
kind: Service
metadata:
  name: broker2-service
  labels:
    name: orionservice-nodeport-svc
spec:
  type: NodePort
  ports:
    - port: 1027
      nodePort: 30150
      name: http
    - port: 443
      nodePort: 31553
      name: https
  selector:
    name: broker2
